version: 2.17
jobs:
  build:
    working_directory: /tmp
    docker:
      - image: circleci/node:10.15.2
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g yarn@latest'
      - restore_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
      - run:
          name: install-npm
          command: yarn install
      - save_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
      - run:
          name: Creating Artifacts
          command: |
            yarn build
      - store_artifacts:
          path: /tmp/artifacts

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy over SSH
          command: |
            yarn install
            yarn build:prod
            scp -r /tmp/build/* root@178.128.161.183:var/www/dmp.milliapps.xyz/
            ssh root@178.128.161.183: "cd /var/www/dmp.milliapps.xyz/; yarn install; yarn start";

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
