version: 2.1
jobs:
  build:
    docker: 
      - image: node:7.4.0
    working_directory: /var/www/dmp.milliapps.xyz/
    steps:
      - checkout
      - run: yarn test
      - run: npm build
    deployment:
      production:
        branch: master
        commands:
          - scp -r master/* root@178.128.161.183:/var/www/dmp.milliapps.xyz/
      
