version: 2.17
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.18.2
    steps:
      - checkout
      - run:
          name: update-npm
          command: npx browserslist --update-db
            sudo npm install -g -f yarn@latest
      - restore_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
      - run:
          name: install-npm
          command: yarn install
      - save_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
      - run:
          name: Creating Artifacts
          command: |
            yarn build
            mkdir -p ~/repo/artifacts
      - store_artifacts:
          path: ~/repo/artifacts

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.18.2
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "6a:f6:52:0c:d6:cc:d5:4b:8f:98:2f:37:f3:78:42:ed"
      - run:
          name: update-npm
          command: npx browserslist --update-db
            sudo npm install -g -f yarn@latest
      - restore_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
      - run:
          name: install-npm
          command: yarn install
      - save_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
      - run:
          name: Deploy over SSH
          command: |
            yarn build
            ssh-keyscan -H 178.128.161.183 >> ~/.ssh/known_hosts 
            scp -r ~/repo/build/* root@178.128.161.183:/var/www/dmp.milliapps.xyz/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
